export enum AvailableLanguages {
  ar,
  bs,
  ca,
  cs,
  da,
  de,
  el,
  en,
  es,
  et,
  fi,
  fr,
  hi,
  hr,
  hu,
  id,
  it,
  ja,
  ko,
  lt,
  lv,
  nl,
  no,
  pl,
  pt,
  ro,
  ru,
  sk,
  sl,
  sr,
  sv,
  tr,
  uk,
  zh,
}

export const LanguagesMap = new Map<number, string>([
  [AvailableLanguages.ar, 'Arabic'],
  [AvailableLanguages.bs, 'Bosnian'],
  [AvailableLanguages.ca, 'Catalan'],
  [AvailableLanguages.cs, 'Czech'],
  [AvailableLanguages.da, 'Danish'],
  [AvailableLanguages.de, 'German'],
  [AvailableLanguages.el, 'Greek'],
  [AvailableLanguages.en, 'English'],
  [AvailableLanguages.es, 'Spanish'],
  [AvailableLanguages.et, 'Estonian'],
  [AvailableLanguages.fi, 'Finnish'],
  [AvailableLanguages.fr, 'French'],
  [AvailableLanguages.hi, 'Hindi'],
  [AvailableLanguages.hr, 'Croatian'],
  [AvailableLanguages.hu, 'Hungarian'],
  [AvailableLanguages.id, 'Indonesian'],
  [AvailableLanguages.it, 'Italian'],
  [AvailableLanguages.ja, 'Japanese'],
  [AvailableLanguages.ko, 'Korean'],
  [AvailableLanguages.lt, 'Lithuanian'],
  [AvailableLanguages.lv, 'Latvian'],
  [AvailableLanguages.nl, 'Dutch'],
  [AvailableLanguages.no, 'Norwegian'],
  [AvailableLanguages.pl, 'Polish'],
  [AvailableLanguages.pt, 'Portuguese'],
  [AvailableLanguages.ro, 'Romanian'],
  [AvailableLanguages.ru, 'Russian'],
  [AvailableLanguages.sk, 'Slovak'],
  [AvailableLanguages.sl, 'Slovenian'],
  [AvailableLanguages.sr, 'Serbian'],
  [AvailableLanguages.sv, 'Swedish'],
  [AvailableLanguages.tr, 'Turkish'],
  [AvailableLanguages.uk, 'Ukrainian'],
  [AvailableLanguages.zh, 'Chinese'],
]);

export const mappedLanguages = Array.from(LanguagesMap.entries()).map(
  (lang) => ({
    value: lang[0],
    label: lang[1],
  })
);
