name: remote ssh command
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 10340
          script: |
            cd ~/apps/oneWord-server
            git fetch origin
            git pull origin master
            git status
            npm install --only=prod
            npm install --only=prod
            pm2 restart node1
